### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by dalelane** [asyncapi/java-template#2]
We should look at whether there is anything left to do before building/publishing the first release of the template

**Comment by derberg** [comment]
I just pinged bot to update this repo with latest workflows (https://github.com/asyncapi/java-template/pull/5), now update name of the template in package.json from `mq-asyncapi-java-template` to `@asyncapi/java-template`. Your PR that updates it should have a `feat` prefix, and release will be triggered automatically after merge, if you added all required `semantic-release` dependencies -> checkout template for generator templates project and it talks about `semantic-release` package and related plugins. You do not have them in the package.json but I see you have `release` property with release configuration.

I also created https://github.com/asyncapi/java-template/releases/tag/v0.0.1 for you already. Otherwise this template would land on NPM directly as 1.0.0...unless this is your plan 😅  so then just add `!` to PR title

**Comment by dan-r** [comment]
Release published!
